name: immcant-env
channels:
 - bioconda
 - conda-forge
 - defaults
dependencies:
 - igblast=1.15.0 
 - r-base=3.6.3
 - rstudio=1.1.456
 - r-alakazam=0.3.0
 - r-shazam=0.2.3
 - r-tigger=0.4.0
 - r-ape=5.4
 
# also need to run: pip3 install changeo --user 

