name: scvelo-env
channels:
  - defaults
dependencies:
  - pip=20.0.2
  - python=3.8.3
  - pip:
    - anndata==0.7.3
    - h5py==2.10.0
    - ipython==7.15.0
    - loompy==3.0.6
    - matplotlib==3.2.1
    - notebook==6.0.3
    - numba==0.49.1
    - numpy==1.18.5
    - packaging==20.4
    - pandas==1.0.4
    - python-igraph==0.8.2
    - scanpy==1.5.1
    - scikit-learn==0.23.1
    - scipy==1.4.1
    - scvelo==0.2.1
    - seaborn==0.10.1
    - umap-learn==0.4.4

